### ISSUE TITLE
How to connect and use tutorial.

### ISSUE THREAD

**Issue by spartandrew18** [aeozyalcin/August2MQTT#1]
Ok I have the yale ble integration installed and have my esphome all set up. I have downloaded the zip file of your repo and created a config.json file with my Bluetooth address and handshake and key. I then used samba share to bring it into the file editor of home assistant. I have terminal ssh open but cannot do any setup.sh or any commands. It will say zsh command not found.

![image](https://user-images.githubusercontent.com/66539077/205426628-94f20559-e9d3-4b5a-ab1e-7858a1c2c31f.png)
![image](https://user-images.githubusercontent.com/66539077/205426646-39e9d403-c525-4254-8c7d-162e7f5db5ec.png)

**Comment by aeozyalcin** [comment]
I just checked in some changes to setup.sh, can you download the latest? Also, you will probably need to make it executable first by running:
```
chmod +x setup.sh
```

Then run it with:
```
./setup.sh
```

I should note, I don't recommend running this on the same machine running your Home Assistant, because that will most likely not play well with Home Assistant, especially if you have other BLE integrations that use the Bluetooth on your machine. I am using a separate Raspberry Pi Zero W that's close to my lock.

**Comment by spartandrew18** [comment]
I will be using the bluetooth on esp32 from esphome

**Comment by aeozyalcin** [comment]
I should note, I have also updated the Readme to hopefully clear things up some more.

**Comment by spartandrew18** [comment]
Do I run this code in ssh editor?

![image](https://user-images.githubusercontent.com/66539077/205427753-29cbf461-8177-45d7-b2d1-fc7b8b88dd23.png)

**Comment by aeozyalcin** [comment]
Yeah, you would run those commands via SSH. That screenshot looks like it's the HA CLI. Sorry I am not super familiar with HA OS, I run regular Raspberry Pi OS. But I will help you out as much as I can.

**Comment by spartandrew18** [comment]
I dont know if I can enter root from Home Assistant

**Comment by spartandrew18** [comment]
But I do have an SSH terminal

**Comment by aeozyalcin** [comment]
Yeah, try the SSH terminal. Odds are, "apt install" command inside setup.sh will fail, but ignore it.

**Comment by spartandrew18** [comment]
Can you hop on Home Assistant Discord?

https://discord.gg/home-assistant

**Comment by aeozyalcin** [comment]
Cool, just got on there. But don't really know how to find you. My username is the same on there.
