### ISSUE TITLE
August lock makes a beeping sound like morse code

### ISSUE THREAD

**Issue by rockstar2020** [aeozyalcin/August2MQTT#2]
Hi there,
Thanks for sharing your project.
I have been using this version of August Bridge Emulator (https://github.com/mtvg/August) for several years and it has been flawless.
But the Raspberry OS I'm using is pretty old and after upgrading I can't make the noble BLE scanner to work as it is built with the old version.
After seeing your project I gave it a try and it does work. Thank you.
My only issue with it is that now my August Lock time to time makes a beeping noise like morse code.
I did some googling and found out this is due to "Bad Handshake". See below:
https://support.august.com/morse-code-sound-SJ8JrpQO8#:~:text=Bad%20Handshake,handshake%20is%20the%20root%20issue.

Do you have any idea what causes this?
I can get the status, lock or unlock with no issues but this noise coming every now and then is very annoying.
Thought of checking to see if you also faced the same issue and perhaps can recommend a way to troubleshoot it.

Thanks in advance

**Comment by aeozyalcin** [comment]
Hey @rockstar2020. Glad to hear you got it working! That's super interesting to hear that your lock is making beeping noises, ~~I didn't even know these locks could make sound~~, I do remember long ago disabling the sound on my lock via the app. I use a Gen 3 Pro lock, and mine does not make any beeping/morse code noises.

Few questions for you:
- What type of August Lock do you have? Gen1, 2, 3, 3 Pro, or 4?
- Had you ever heard this sound before you started using this repo?
- How often is the noise happening?
- How are you running the MQTT bridge? If you have access to the Python terminal output, that would be helpful to share. I would especially recommend trying to see if you can catch the terminal output while the lock is making the noise. Then we can see if the bridge was trying to reconnect via BLE and do a handshake while the beeping occured.

**Comment by rockstar2020** [comment]
Hi @aeozyalcin, thanks for your reply.
My August Lock is Gen 1 and since the beginning I installed this repo (https://github.com/mtvg/August) and has been functioning flawlessly for past several years.
Initially I installed this repo on a RPI 3B+ with Raspian Stretch (Jessie) OS. It's clear how old my setup is. :)
All this time I never experienced this noise coming out of the lock.
In fact, I did insert the backup SD card to my RPI again and I don't hear such noise coming out of the lock.
So I'm pretty sute it's got something to do with the code.
I added few loggers in your code to capture errors and noticed that this issue happens when bluetooth tries to establish a connection. Basicaly that's where the handshake goes wrong.
So for example, if I check status of the lock 9 times, 10th times it throws an error "Connection probably failed" (which I think you are familiar with it) and that's when the beeps are heard. It's very random though and happens when I run lock/unlock commands!
I'm still investigating and the reason I left a message here was to see if you also exprienced the same.
I'll keep you posted.

Thanks again

**Comment by aeozyalcin** [comment]
@rockstar2020 got it. Are you using cli.py inside the folder, or mqtt_august_bridge.py?

> So for example, if I check status of the lock 9 times, 10th times it throws an error "Connection probably failed"

How are you checking the lock status?

On the Gen3 lock that i have, if i don't generate BLE traffic once every 90 seconds, the lock terminates the BLE connection. To work around this, the bridge checks lock status automatically every 60 seconds to keep the connection alive. I wonder if this timeout is lower on your lock (earlier gens).

**Comment by rockstar2020** [comment]
Hi again, no I'm not using cli.py.
I have made slight adjustmnets to your mqtt_august_bridge.py and only connect when I need to check the status, lock or unlock the August Lock.
I have a simple script on another Node Red server which sends an MQTT message to check the status of the lock every 3 min so I doubt the timeout is an issue.

Here is part of my code where it gets triggered based on MQTT message received:

def on_mqtt(client, userdata, message):
   command = str(message.payload.decode("utf-8"))
   i=0
   success=False
   try:
     if (not lock.connect()):
        lock.connect()
     if(command == 'lock'):
        for i in range(10):
           if (lock.is_connected()):
              if (not lock.force_lock()):
                 if (lock.force_lock()):
                    success=True
           if (success):
              client.publish("august/status", 'lock')
              break
     elif(command == 'unlock'):
        for i in range(10):
           if (lock.is_connected()):
              if (not lock.force_unlock()):
                 if (lock.force_unlock()):
                    success=True
           if (success):
              client.publish("august/status", 'unlock')
              break
     elif(command == 'status'):
        stat = lock.getStatus()
        client.publish("august/status", stat)
     elif(command == 'battery'):
        battery = int(lock.getBattery())/100
        client.publish("august/battery", battery)
     lock.disconnect()
     print("The command of [" + command + "] executed successfully after " + i + " tries")
     logger.info("The command of [" + command + "] executed successfully after " + i + " tries")
   except:
     print('An error occured while executing the command')

**Comment by rockstar2020** [comment]
By the way, I improved my code a little as follows and I'll keep observing to see if I can nail down to where exactly the issue could be. I'll keep you posted. Have a nice weekend!

def on_mqtt(client, userdata, message):
   command = str(message.payload.decode("utf-8"))
   i=1
   try:
     if not lock.is_connected():
        connection=lock.connect()
     if not connection:
         lock.connect()
     print('Connectin to lock is: ' + str(connection))
     if(command == 'lock'):
        for i in range(10):
           if (connection):
              if (lock.force_lock()):
                 client.publish("august/status", 'lock')
                 break
              else:
                 time.sleep(0.5)
     elif(command == 'unlock'):
        for i in range(10):
           if (connection):
              if (lock.force_unlock()):
                 client.publish("august/status", 'unlock')
                 break
              else:
                 time.sleep(0.5)
     elif(command == 'status'):
        stat = lock.getStatus()
        client.publish("august/status", stat)
     elif(command == 'battery'):
        battery = int(lock.getBattery())/100
        client.publish("august/battery", battery)
     lock.disconnect()
     print("The command of [" + command + "] executed successfully after " + str(i) + " tries")
     logger.info("The command of [" + command + "] executed successfully after " + str(i) + " tries")
   except:
     print('An error occured while executing the command')

**Comment by aeozyalcin** [comment]
> By the way, I improved my code a little as follows and I'll keep observing to see if I can nail down to where exactly the issue could be. I'll keep you posted. Have a nice weekend!
> 
> def on_mqtt(client, userdata, message): command = str(message.payload.decode("utf-8")) i=1 try: if not lock.is_connected(): connection=lock.connect() if not connection: lock.connect() print('Connectin to lock is: ' + str(connection)) if(command == 'lock'): for i in range(10): if (connection): if (lock.force_lock()): client.publish("august/status", 'lock') break else: time.sleep(0.5) elif(command == 'unlock'): for i in range(10): if (connection): if (lock.force_unlock()): client.publish("august/status", 'unlock') break else: time.sleep(0.5) elif(command == 'status'): stat = lock.getStatus() client.publish("august/status", stat) elif(command == 'battery'): battery = int(lock.getBattery())/100 client.publish("august/battery", battery) lock.disconnect() print("The command of [" + command + "] executed successfully after " + str(i) + " tries") logger.info("The command of [" + command + "] executed successfully after " + str(i) + " tries") except: print('An error occured while executing the command')

Ok I think I follow what you are doing there. Few questions: 

- Was the lock making the beeping sound even when you used the "stock" mqtt_august_bridge.py? Did you get a chance to try it as-is?
- Did you comment out the following while loop? 
```
while(1):
    if(mqtt_event.wait(75)): #we got an mqtt event
        mqtt_event.clear()
        ...
```
- If the complete contents of that while loop is not commented out, it will generate a status command to the lock every 75 seconds to keep the BLE connection alive. If not careful, this could cause a race condition if the while loop was attempting to talk to the lock while you send an MQTT command at the same time. That's why I have the while loop as the only place that can issue commands to the lock to avoid race conditions.

**Comment by rockstar2020** [comment]
At first I used mqtt_august_bridge.py but since I ntoiced the beeping sound I started to slim down your code and only connect to the lock when I needed.

**Comment by aeozyalcin** [comment]
Ok let me know if you discover anything. The other thing I'm going to recommend trying is to disable the lock sounds in the app and see if it makes the beeping go away.

**Comment by rockstar2020** [comment]
Hi @aeozyalcin,
Ok, I think the beeping sound is coming after the time out of some sort of notification is reached.
Basically the error message of "Notification Timed Out" is caught in below mentioned sesction of your code in session.py:
As mentioned before I'm sending a MQTT messgae every 3min to check the status of the lock.
This error repeats 3 to 5 times in a row (ie up to 15min) and then it starts responding to Status Inquiries with no issues.
Obviously this error may also come when Lock or Unlock command is sent. 
Also sometimes I get other error message (Security checksum mismatch) as well but it doesn't seem to lead to the lock making any noise.
Any thoughts?

Thanks in advance

`def _write(self, command: bytearray): 

      if self.cipher_encrypt is not None:
            plainText = command[0x00:0x10]
            cipherText = self.cipher_encrypt.encrypt(plainText)
            util._copy(command, cipherText)

      self.peripheral.withDelegate(self.delegate)
      self.write_characteristic.write(command, True)

      if(self.delegate.data is None and self.peripheral.waitForNotifications(5) is False):
            print("Notification timed out")
            return None
      else:
            temp = self.delegate.data
            self.delegate.data = None
            #return self.delegate.data
            return temp`

**Comment by aeozyalcin** [comment]
The first thing that comes to mind is that you said you are polling for status every 3 minutes. The lock will disconnect if it doesn't get any traffic for 90 seconds. That could explain the "Notification timed out" error. The code normally polls the lock every 75 seconds to keep the connection alive.

**Comment by rockstar2020** [comment]
Thanks but I'm not constantly connected to the lock. 
In my code I connect, get the status and then disconnect. 
Can the timeout still be an issue?

**Comment by aeozyalcin** [comment]
Gotcha, if you are not staying connected, then it shouldn't be an issue.

Did you comment out the following in mqtt_august_bridge.py? This is the portion that attempts to check in with the lock every 75 seconds. In your case, it should be commented, and probably just be replaced with an empty while loop.
```
while(1):
    if(mqtt_event.wait(75)): #we got an mqtt event
        mqtt_event.clear()
        ...
```

**Comment by rockstar2020** [comment]
Thank you @aeozyalcin for your response.
Well, I'm not using mqtt_august_bridge.py.
Attached is my code for your reference:

[august.pdf](https://github.com/aeozyalcin/August2MQTT/files/10229427/august.pdf)

**Comment by aeozyalcin** [comment]
I saw you closed the issue. Were you able to root cause it?

**Comment by rockstar2020** [comment]
> I saw you closed the issue. Were you able to root cause it?

Hi @aeozyalcin , unfortunately not. I think either this code works well with newer version of August lock or perhaps you already turned off the alarm from your app and most likely that's the reason you don't hear the annoying beeps. 
I gave up finally and went back to my old Raspbian Stretch and the Node-Red code which works flawlessly with my lock. 

However I am still very much interested to give it another try later because I definitely prefer my OS to stay updated. 

Thanks for your follow up and happy holidays!
Chess
